### ISSUE TITLE
Run never ends

### ISSUE THREAD

**Issue by SUPERETDUPER** [miguelcordovam/leJOS_plugin#4]
Even after the program ends on the EV3, in IntelliJ, the "Run" is still running and I must press the stop or terminate to end it

**Comment by SUPERETDUPER** [comment]
If you give me pointers on how to fix this I am willing to contribute and help

**Comment by miguelcordovam** [comment]
Hi, thanks for your comments. Actually I already have the fix for this. I will release next version soon.

**Comment by SUPERETDUPER** [comment]
Great! Looking forward to the release!
